[build]
publish = "public"
command = "hugo --gc --minify"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.89.2"

[context.production.environment]
HUGO_VERSION = "0.89.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "false"
